# Generated by Django 3.2.13 on 2022-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data about the Event with keys and values, e.g. description: Client Terminated', verbose_name='Event Data'),
        ),
    ]
