from setuptools import setup, find_packages

setup(
    name="maguire",
    version="0.1",
    url='https://github.com/picsadotcom/maguire',
    license='BSD',
    author='Picsa',
    author_email='admin@picsa.com',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django<2.0',
        'djangorestframework==3.6.4',
        'django-rest-auth',
        'dj-database-url',
        'psycopg2',
        'raven',
        'gunicorn',
        'django-filter',
        'whitenoise',
        'celery',
        'redis',
        'pytz',
        'python-dateutil',
        'django-cors-middleware',
        'django-reversion',
        'graphene<2.0',
        'graphene-django<2.0.0',
        'graphql-core<2.0',
        'pendulum',
        'django-role-permissions==1.2.1',
        'django-celery-beat',
        'boto3',
        'django-storages',
        'opbeat',
        'postmarker',
        'django-extensions',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
