from setuptools import setup, find_packages

setup(
    name="maguire",
    version="0.1",
    url='https://github.com/picsadotcom/maguire',
    license='BSD',
    author='Picsa',
    author_email='admin@picsa.com',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django<4',
        'django-celery-beat',
        'django-cors-headers',
        'django-filter',
        'django-extensions',
        'django-rest-auth',
        'django-reversion',
        'django-role-permissions',
        'django-storages',
        'djangorestframework',
        'dj-database-url',
        'psycopg2-binary',
        'raven',
        'gunicorn',
        'whitenoise',
        'celery',
        'redis',
        'pytz',
        'python-dateutil',
        'graphene-django',
        'pendulum',
        'postmarker',
        'boto3',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.8',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
