from setuptools import setup, find_packages

setup(
    name="maguire",
    version="0.1",
    url='https://github.com/picsadotcom/maguire',
    license='BSD',
    author='Picsa',
    author_email='admin@picsa.com',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django<2.2',
        'djangorestframework',
        'django-rest-auth',
        'dj-database-url',
        'psycopg2-binary',
        'raven',
        'gunicorn',
        'django-filter',
        'whitenoise',
        'celery',
        'redis',
        'pytz',
        'python-dateutil',
        'django-cors-middleware',
        'django-reversion',
        # https://github.com/graphql-python/graphene/releases
        'graphene==2.1.3',
        # https://github.com/graphql-python/graphene-django/releases
        'graphene-django==2.2.0',
        # https://github.com/graphql-python/graphql-core/releases
        'graphql-core==2.1',
        'graphql-relay<0.5',
        'pendulum',
        'django-role-permissions',
        'django-celery-beat',
        'boto3',
        'django-storages',
        'postmarker',
        'django-extensions',
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'License :: OSI Approved :: BSD License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
