# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('loaded', 'Loaded'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
