# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0002_auto_20180213_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='last_error',
            field=models.TextField(blank=True, help_text='The error message received on the last attempt to load the debit', null=True, verbose_name='Last Error'),
        ),
        migrations.AddField(
            model_name='debit',
            name='load_attempts',
            field=models.IntegerField(default=0, help_text='Number of times maguire has attmepted to load the debit', verbose_name='Load Attempts'),
        ),
    ]
