# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits', '0003_auto_20180213_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
